#!/usr/bin/env bash
# Using if and while statement constrcut to print

counter=1

while [ $counter -le 10 ]
do
	if [ $counter -eq 10 ]
	then
		echo "Hi"
	fi

	echo "Best School"
	
	((counter++))
done
