#!/usr/bin/env bash
# Using if and while statement constrcut to print

counter=0

while [ $counter -lt 10 ]
do
        if [ $counter -eq 3 ]
        then
                echo "bad luck"
	elif [ $counter -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
        ((counter++))
done

