#!/usr/bin/env bash
# A script that displays the content of the current directory in a list format
# only displays the part of the name after the first dash

list=$(ls)
for i in $list; do
    echo "$i" | cut -d '-' -f2
done
