#!/usr/bin/env bash

# Key pair information
private_key_file="school"
key_bits=4096
passphrase="betty"
# Generate RSA key pair
ssh-keygen -t rsa -b "$key_bits" -f "$private_key_file" -N "$passphrase"

echo "RSA key pair created successfully."
